evenement_participation:
    resource: "@EvenementBundle/Controller/participationController.php"
    type:     annotation

evenement_evenement:
    resource: "@EvenementBundle/Controller/evenementController.php"
    type:     annotation

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /



solidarity:
    resource: "@SolidarityBundle/Resources/config/routing.yml"
    prefix:   /solidarity


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
