offreemploi_offreemploi:
    resource: "@OffreemploiBundle/Controller/offreemploiController.php"
    type:     annotation

formation_formation:
    resource: "@FormationBundle/Controller/formationController.php"
    type:     annotation

offreemploi:
    resource: "@OffreemploiBundle/Resources/config/routing.yml"
    prefix:   /

formation:
    resource: "@FormationBundle/Resources/config/routing.yml"
    prefix:   /

service_servicesante:
    resource: "@ServiceBundle/Controller/servicesanteController.php"
    type:     annotation

service_hebergement:
    resource: "@ServiceBundle/Controller/hebergementController.php"
    type:     annotation

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

evenement_participation:
    resource: "@EvenementBundle/Controller/participationController.php"
    type:     annotation

evenement_evenement:
    resource: "@EvenementBundle/Controller/evenementController.php"
    type:     annotation




actualite_actualite:
    resource: "@ActualiteBundle/Controller/ActualiteController.php"
    type:     annotation

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /

solidarity:
    resource: "@SolidarityBundle/Resources/config/routing.yml"
    prefix:   /solidarity


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
