service_servicesante:
    resource: "@ServiceBundle/Controller/servicesanteController.php"
    type:     annotation

service_hebergement:
    resource: "@ServiceBundle/Controller/hebergementController.php"
    type:     annotation

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

evenement_participation:
    resource: "@EvenementBundle/Controller/participationController.php"
    type:     annotation

evenement_evenement:
    resource: "@EvenementBundle/Controller/evenementController.php"
    type:     annotation

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /



actualite_actualite:
    resource: "@ActualiteBundle/Controller/ActualiteController.php"
    type:     annotation

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /

solidarity:
    resource: "@SolidarityBundle/Resources/config/routing.yml"
    prefix:   /solidarity


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
