publicite_publicite:
    resource: "@PubliciteBundle/Controller/PubliciteController.php"
    type:     annotation

publicite:
    resource: "@PubliciteBundle/Resources/config/routing.yml"
    prefix:   /publicite

evenement_participation:
    resource: "@EvenementBundle/Controller/participationController.php"
    type:     annotation

evenement_evenement:
    resource: "@EvenementBundle/Controller/evenementController.php"
    type:     annotation

evenement_theme:
    resource: "@EvenementBundle/Controller/ThemeController.php"
    type:     annotation

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /



actualite_actualite:
    resource: "@ActualiteBundle/Controller/ActualiteController.php"
    type:     annotation

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /
service_hebergement:
    resource: "@ServiceBundle/Controller/hebergementController.php"
    type:     annotation
    prefix:   /actualite

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /hebergement
service_servicesante:
    resource: "@ServiceBundle/Controller/servicesanteController.php"
    type:     annotation

servicesante:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /servicesante

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

reclamation_reclamation:
    resource: "@ReclamationBundle/Controller/reclamationController.php"
    type:     annotation

solidarity:
    resource: "@SolidarityBundle/Resources/config/routing.yml"
    prefix:   /solidarity

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
reclamation_traitement:
        resource: "@ReclamationBundle/Controller/TraitementController.php"
        type:     annotation
traitement:
        resource: "@ReclamationBundle/Resources/config/routing.yml"
        prefix:   /traitement

fos_user_registration_confirmed:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"