<?php

namespace ServiceBundle\Repository;

/**
 * hebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
