<?php

namespace ServiceBundle\Repository;

/**
 * servicesanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicesanteRepository extends \Doctrine\ORM\EntityRepository
{
}
