<?php

namespace OffreemploiBundle\Repository;

/**
 * offreemploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offreemploiRepository extends \Doctrine\ORM\EntityRepository
{
}
